package sir.mazer.ledpanel.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFFFB2B6)
val md_theme_dark_onPrimary = Color(0xFF68001A)
val md_theme_dark_primaryContainer = Color(0xFF920029)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDADA)
val md_theme_dark_secondary = Color(0xFFE6BDBE)
val md_theme_dark_onSecondary = Color(0xFF44292B)
val md_theme_dark_secondaryContainer = Color(0xFF5D3F40)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDADA)
val md_theme_dark_tertiary = Color(0xFFE7C08E)
val md_theme_dark_onTertiary = Color(0xFF432C06)
val md_theme_dark_tertiaryContainer = Color(0xFF5C421A)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF201A1A)
val md_theme_dark_onBackground = Color(0xFFECE0DF)
val md_theme_dark_surface = Color(0xFF201A1A)
val md_theme_dark_onSurface = Color(0xFFECE0DF)
val md_theme_dark_surfaceVariant = Color(0xFF524343)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C2)
val md_theme_dark_outline = Color(0xFF9F8C8C)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1A)
val md_theme_dark_inverseSurface = Color(0xFFECE0DF)
val md_theme_dark_inversePrimary = Color(0xFFB71C3C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB2B6)
val md_theme_dark_outlineVariant = Color(0xFF524343)
val md_theme_dark_scrim = Color(0xFF000000)